services:
  - type: web
    name: auth-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn auth_api.wsgi
    envVars:
      - key: DEBUG
        value: "False"
